#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-leveldbjni
Version  : 1.8
Release  : 4
URL      : https://github.com/fusesource/leveldbjni/archive/leveldbjni-1.8.tar.gz
Source0  : https://github.com/fusesource/leveldbjni/archive/leveldbjni-1.8.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/fusesource/leveldbjni/leveldbjni-project/1.8/leveldbjni-project-1.8.pom
Source2  : https://repo1.maven.org/maven2/org/fusesource/leveldbjni/leveldbjni-all/1.8/leveldbjni-all-1.8.jar
Source3  : https://repo1.maven.org/maven2/org/fusesource/leveldbjni/leveldbjni-all/1.8/leveldbjni-all-1.8.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mvn-leveldbjni-data = %{version}-%{release}

%description
# LevelDB JNI
## Description
LevelDB JNI gives you a Java interface to the
[LevelDB](http://code.google.com/p/leveldb/) C++ library
which is a fast key-value storage library written at Google
that provides an ordered mapping from string keys to string values..

%package data
Summary: data components for the mvn-leveldbjni package.
Group: Data

%description data
data components for the mvn-leveldbjni package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/fusesource/leveldbjni/leveldbjni-project/1.8
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/fusesource/leveldbjni/leveldbjni-project/1.8/leveldbjni-project-1.8.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/fusesource/leveldbjni/leveldbjni-all/1.8
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/fusesource/leveldbjni/leveldbjni-all/1.8/leveldbjni-all-1.8.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/fusesource/leveldbjni/leveldbjni-all/1.8
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/fusesource/leveldbjni/leveldbjni-all/1.8/leveldbjni-all-1.8.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/fusesource/leveldbjni/leveldbjni-all/1.8/leveldbjni-all-1.8.jar
/usr/share/java/.m2/repository/org/fusesource/leveldbjni/leveldbjni-all/1.8/leveldbjni-all-1.8.pom
/usr/share/java/.m2/repository/org/fusesource/leveldbjni/leveldbjni-project/1.8/leveldbjni-project-1.8.pom
